### ISSUE TITLE
Ships

### ISSUE THREAD

**Issue by offsky** [danpaulson/swgoh.gg.public#11]
Just putting a placeholder issue here, since Im sure you already thought about adding ships to swgoh.gg. 

I can help if you need help.

**Comment by scoot1585** [comment]
Thanks for the offer, but the biggest thing preventing ships is a pretty large rewrite I am working on that had to get put on hold for work purposes.  But I hope to get those added!

Thanks for the placeholder and just for documentation my plans are:
- Sync ships
- Create ship listing/details
- Create ship arena tracker
- Update meta report

**Comment by scoot1585** [comment]
Going to close this as ships are in.  We have to get our syncing process down before we get into syncing ships at arena payout times because of the gigantic hit this would cause of syncing everyone's account twice now, especially during US/EU prime times.  Having the ship payout an hour later is not very nice for us currently.
