### ISSUE TITLE
Arena rank doesn't match character sheet

### ISSUE THREAD

**Issue by Githomie** [danpaulson/swgoh.gg.public#151]
When syncing your account, it updates your character sheets etc.. immediately, and updates your rank, but on the chart that shows your rank over time, it doesn't update it when you sync it.

So for example, I sync directly after rewards come in for the day, and my profile page shows my rank correctly, but the chart only refreshes some hours later, at which point my rank has usually changed, so it's consistently off on what my rank was for the day (unless I wasn't attacked at all following reward payout).

In theory, the timezone setting should take care of this, but it seems to always auto-sync about 2 hours after the rewards come in (even with timezone set correcly) and ignores the rank from a manual sync.

**Comment by danpaulson** [comment]
This is a complicated problem - we only sync Arena Rating at your payout so that if you want to refresh your roster it doesn't add a marker. That said, our payout syncs are insanely bogged down right now - some have over 50,000 accounts we have to sync. We are investigating how to handle this, but for now going to close this as WAI.
