### ISSUE TITLE
autosync not working

### ISSUE THREAD

**Issue by oli20021978** [danpaulson/swgoh.gg.public#174]
my account can't be synced automatically.

https://swgoh.gg/u/legoli/

**Comment by apazga** [comment]
Hi,

It seems syncing is not working since yesterday.
I tried editing my settings again and everything was empty. Filled everything again (ally code & ID) and after hitting save... Django crash!

![screenshot 2018-03-01 10 14 46](https://user-images.githubusercontent.com/6894350/36836420-8c604ed4-1d39-11e8-9209-6526cab49dda.png)

If you need any test or debug info, just tell me.

**Comment by jsaraiva** [comment]
And it appears to be working again.
Problem is, I tried entering my player ID, and now _all_ my data that did not come from sync (squads) was lost.

**Comment by yodaman98** [comment]
I've had similar problems since yesterday 6pm EST. My profile doesn't show anything, its totally blank and not synced to my SWGOH account anymore. I've tried inputing my player ID and it won't work, I've tried using the player ID tool and it won't find me in the system. Is this happening to anyone else?

https://swgoh.gg/u/yodaman98/

**Comment by ShayneH1973** [comment]
Having the exact same issue, and also got the “Forbidden (403)” comment just as I thought it was going to work.

**Comment by jaredpoe** [comment]
Have had this same issue since 2/27 patch. https://swgoh.gg/u/atosite/

**Comment by apazga** [comment]
Just comment I try to sync (adding ally and personal ID again), and it's working now.

**Comment by ylixa** [comment]
I’m in an endless loop from syncing to being directed to fill out my profile to syncing .......

**Comment by apazga** [comment]
It seems it's working from yesterday
