### ISSUE TITLE
I am not able to login to my account:  I

### ISSUE THREAD

**Issue by cospeito** [danpaulson/swgoh.gg.public#211]
I am not able to login to my account:

I have not been able to login for the last couple of weeks or so because my e-mail address is too long and does not fit in the field.
The login field had sufficient character space before, but now the last two letters of my e-mail address do not fit. Thus I cannot log in to my account anymore.

**Comment by HROTHGAR666** [comment]
Same here!

**Comment by danpaulson** [comment]
Can you provide your email address?

**Comment by HROTHGAR666** [comment]
matthew.biesiadecki.666@gmail.com

**Comment by HROTHGAR666** [comment]
matthew.biesiadecki.666@gmail.com


Sent from my Sprint Samsung Galaxy Note5.
-------- Original message --------From: Dan Paulson <notifications@github.com> Date: 3/15/18  6:41 PM  (GMT-08:00) To: "danpaulson/swgoh.gg.public" <swgoh.gg.public@noreply.github.com> Cc: HROTHGAR666 <matthew.biesiadecki.666@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [danpaulson/swgoh.gg.public] I am not able to login to my
  account: I (#211) 
Can you provide your email address?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/danpaulson/swgoh.gg.public","title":"danpaulson/swgoh.gg.public","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/danpaulson/swgoh.gg.public"}},"updates":{"snippets":[{"icon":"PERSON","message":"@danpaulson in #211: Can you provide your email address?"}],"action":{"name":"View Issue","url":"https://github.com/danpaulson/swgoh.gg.public/issues/211#issuecomment-373576776"}}}

**Comment by danpaulson** [comment]
@HROTHGAR666 I don't see any user with that username. Are you trying to create an account or do you already have one?

**Comment by cospeito** [comment]
lasfaldassonunaloteria@gmail.com

**Comment by HROTHGAR666** [comment]
i am trying to create an account, but in the email address field it will not let me put my full email address.
matthew.biesiadecki.666@gmail.com
thanks.


Sent from my Sprint Samsung Galaxy Note5.
-------- Original message --------From: Dan Paulson <notifications@github.com> Date: 3/16/18  9:24 AM  (GMT-08:00) To: "danpaulson/swgoh.gg.public" <swgoh.gg.public@noreply.github.com> Cc: HROTHGAR666 <matthew.biesiadecki.666@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [danpaulson/swgoh.gg.public] I am not able to login to my
  account: I (#211) 
@HROTHGAR666 I don't see any user with that username. Are you trying to create an account or do you already have one?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/danpaulson/swgoh.gg.public","title":"danpaulson/swgoh.gg.public","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/danpaulson/swgoh.gg.public"}},"updates":{"snippets":[{"icon":"PERSON","message":"@danpaulson in #211: @HROTHGAR666 I don't see any user with that username. Are you trying to create an account or do you already have one?"}],"action":{"name":"View Issue","url":"https://github.com/danpaulson/swgoh.gg.public/issues/211#issuecomment-373767426"}}}

**Comment by danpaulson** [comment]
This should be fixed!
