### ISSUE TITLE
mod pages down

### ISSUE THREAD

**Issue by kallko** [danpaulson/swgoh.gg.public#219]
Hi i try to receive data for working with mods. After may be 50 requests for different users pages with mods - down

May be you can create API for mods or tell me where i can receive it another way? 

kallko_andrey@yahoo.co.uk

skype : tri___ton

**Comment by Haidebej** [comment]
https://swgoh.gg/u/haidon/mods/

As of the last patch, my total number of mods showed as (0). 

Today, it shows as 50. Based on what I see on my list, I believe it is only showing the mods on the characters to which I have made changes since the last patch. 

I have added mods to Logray today; I expect his mods will show in the list after the next sync.

**Comment by Haidebej** [comment]
I checked today, and see all 574 of my mods. Whatever was holding things up seems to have been resolved.

**Comment by danpaulson** [comment]
Hopefully this is resolved for all!
