### ISSUE TITLE
Ship Power wrong in my profile

### ISSUE THREAD

**Issue by CalyPhornia** [danpaulson/swgoh.gg.public#254]
https://swgoh.gg/u/calyphornia/ships/tie-silencer/ // Power: 4559

Ingame power of my tie silencer:
https://imgur.com/a/YESrew9 // Power: 4754

I think the calculation of crew power with multiplier is wrong

**Comment by scoot1585** [comment]
This is actually most likely related to an issue we have with ship being dropped from the actual ship data we have.  Your Kylo ship is missing skills because of that basically.  

Unfortunately we probably won't be fixing this in the old code, as I know the new sync code has this all calculating correctly and saving all the ship stats and skills correctly.

Thanks for the report, but bear with us til we get the new update out we talked about here: https://www.reddit.com/r/SWGalaxyOfHeroes/comments/8jhb3m/swgohgg_upcoming_changes/
