### ISSUE TITLE
Guild not syncing

### ISSUE THREAD

**Issue by celsogbj** [danpaulson/swgoh.gg.public#265]
Hi,

My guild info has not synced for 2 days. Is that normal? What can we do To solve this problem?

The link To my guild profile is: https://swgoh.gg/g/2430/team-treta/

Thanks in advance,
Celso

**Comment by DylanTusler** [comment]
I think I remember the devs commenting here at one point that only top 250 guilds are synched. Which makes sense if you are synching via the game. But not if you are getting the info from your own database.

**Comment by scoot1585** [comment]
I just looked at your guild info and what I can retrieve just now and they are really close, we sync guild gp and total member count every night if you have more than 10 members, otherwise all guilds get synced on sundays.

Things like raid points, guild rank, etc only get updated if we see you in top 200 lists.  if you fall out of that we are unable to know that info.

If the GP or member count isn't updating, or you are definitely in top 200 guilds and the raid/rank isn't updating let me know.  But I am going to close this
