### ISSUE TITLE
WRONG PG IN SHIPS

### ISSUE THREAD

**Issue by manguicho** [danpaulson/swgoh.gg.public#266]
Hi, the pg in ships is wrong. please check it.

**Comment by scoot1585** [comment]
it is off because of some "old sync" issues.  Unfortunately we are not going to work on this right now as we are dedicating all time to the new sync code which should be much better and I can assure you is calculating everything correctly for all my units.

Read this thread for info on the upcoming change, and thanks for using the site!

https://www.reddit.com/r/SWGalaxyOfHeroes/comments/8jhb3m/swgohgg_upcoming_changes/
