### ISSUE TITLE
Arena Info - Graph

### ISSUE THREAD

**Issue by TobyCooper** [danpaulson/swgoh.gg.public#268]
I see no Arena Info (History Graph)
https://swgoh.gg/u/cooper23/

Would be great if you fix this.

**Comment by scoot1585** [comment]
It seems to be syncing now (I can see a few data points).  It could have been during a hiccup with syncing we had, where we were having performance issues recording data.  Our new sync rewrite should be much better overall https://www.reddit.com/r/SWGalaxyOfHeroes/comments/8jhb3m/swgohgg_upcoming_changes/

Let me know if this isn't actually fixed with what you were expecting
