### ISSUE TITLE
Qui-Gon Jinn Ability Classes does not include Foresight

### ISSUE THREAD

**Issue by azgo** [danpaulson/swgoh.gg.public#270]
Hi,
It's a minor thing, might be addressible more easily.
QGJ has whole team Foresight in his Agility Training Zeta.

Would you make him give this Ability Class also?

Thanks for all of your marvelous work!

**Comment by scoot1585** [comment]
Thanks for the report.  I actually had to think about the correct way we should fix this.  Currently, we processed leader abilities differently than non leader abilities.  If I would have added Foresight to the old system, all you would see for QGJ, is `Leader: Foresight` which is useful, but doesn't solve your actual issue.  So I also made it so that Leader abilities can now register the non leader ability classes as well.  So QGJs leader skill now gives `Leader: Foresight` and `Foresight`

**Comment by azgo** [comment]
Awesome, thanks!
