### ISSUE TITLE
Arena synch not happening for my profile

### ISSUE THREAD

**Issue by DylanTusler** [danpaulson/swgoh.gg.public#272]
Just noticed that arena positions for my profile have not updated since Wed May 23. So the last two days do not appear. Coincidentally, both these days I was at #1.

Other parts of my profile are scynching fine such as characters. I can see two toons I upgraded to 7* this morning showing as 7* toons in my profile after a sync.

https://swgoh.gg/u/dylan72/

Above the graph it shows 1 as my highest rank, so I think the data is there, it's just not displaying on the graph.

**Comment by stashamarie** [comment]
This is the second time after a huge update that my swgoh.gg account was basically deleted.  Since the update my arena is not syncing at all.  And in the past when it did sync, it was never at the payout rank, even if I manually sync it right away, it will show the wrong rank if someone bumps me out of 1st within 15-30 min after payout.  [https://swgoh.gg/u/esmae/](url)

**Comment by Celebnasse** [comment]
I'm having the same issue.  My latest update is May 22nd.  Nothing on my profile is updating since the new version of the game came out.

https://swgoh.gg/u/celebnasse/

**Comment by Celebnasse** [comment]
After forcing a sync, it seems to have updated my characters, ships and mods now.. but still not my arena rank.

**Comment by DylanTusler** [comment]
Synch happened tonight, but it's missing the intervening nights.

**Comment by danpaulson** [comment]
Unfortunately we don't have access to previous nights. This should happen less frequently (or, god willing, never) once we move to our new backend.
