### ISSUE TITLE
profile

### ISSUE THREAD

**Issue by jharbour5** [danpaulson/swgoh.gg.public#42]
the address for my profile changed. it was https://swgoh.gg/u/jharbour#3192 - now it is https://swgoh.gg/u/jharbour%233192/

**Comment by scoot1585** [comment]
The pound sign in web terms is a reserved character.  it signifies a URL fragment.  If you tried to use it, it would build an invalid URL since you would actually be attempting to go to `https://swgoh.gg/u/jharbour` and then you would go to fragment `#3192` on the page which wouldnt exist so it wouldnt do anything

I am going to close this, since it is working as intended.

**Comment by jharbour5** [comment]
Can we change the name on my profile to just jharbour ?

**Comment by scoot1585** [comment]
yup, I updated it to just `jharbour` now.  should be good to go.

**Comment by jharbour5** [comment]
Thank you
