### ISSUE TITLE
[Known Issue] Guilds are not syncing / names aren't updating / players are missing

### ISSUE THREAD

**Issue by danpaulson** [danpaulson/swgoh.gg.public#85]
Consolidating as it's an active issue - we are working on it.

**Comment by johnsmark** [comment]
Thanks for the update - much appreciated.

**Comment by Tigershark2005** [comment]
I believe my guild changed names at some point from "The Unforsaken" to "TIE Unforsaken", the name change is not reflected but it looks like the roster is staying up to date. Guild power is extremely off but that may be because not all members are listed (have registered) and possibly you're just adding up the info you have instead of pulling from the EA database. Let me know if there's anything you need from me.
